# -*- coding: utf-8 -*-
#
# Copyright (c) 2017 Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.


# Example on how to use Ansible to configure AOS-Switches
# This block will execute a set of different configurations via tasks
- hosts: branch*_switches
  connection: local
  gather_facts: no
  tasks:
    - name: Confgiure Switch
      block:
        # Login to ArubaOS switches
        - name: Login
          include: aruba_task_lists/aos_switch/login_switch.yml

        # Configure ArubaOS switches using anycli rest option
        - name: anycli configure
          include: aruba_task_lists/aos_switch/anycli.yml command="{{item}}"
          with_items:
            - "configure terminal"
            - "vlan 233"

        # Configure ArubaOS Switches to upload new cert
        - name: Upload TA cert
          include: aruba_task_lists/aos_switch/cert_upload.yml
          vars:
            path_to_cert: "files/ta_cert.cer"
            ta_name: "TAcert"

        # Configure ArubaOS switches for DNS
        - name: Set dns
          include: aruba_task_lists/aos_switch/set_dns.yml
          vars:
            dns_ip1: "10.80.2.219"
            dns_name1: "tmelab.net"

        # Set SNMP server community
        - name: Set SNMP server community
          include: aruba_task_lists/aos_switch/create_snmp_community.yml
          vars:
            community: "Test123"
            access_type: "manager"
            restricted: False

        # Set SNMP server hosts with community
        - set_fact:
            snmp_host:
              host_ip: "10.3.7.5"
              community: "Test123"
              trap_level: "all" #  accespt all/critical/debug/not_info/none
              informs: True
              use_oobm: True
        - name: Set snmp hosts
          include: aruba_task_lists/aos_switch/snmp_server_host.yml
          vars:
            host_data: "{{ snmp_host }}"

        # Set Jumbo VLANs
        - name: Set Jumbos VLANs
          include: aruba_task_lists/aos_switch/set_jumbo.yml
          vars:
            vlan: "233"

        # Configure SpanningTree Globally
        - name: Configure SpanningTree Globally
          include: aruba_task_lists/aos_switch/spanning_tree_global.yml
          vars:
            status: "disable" # or "enable"
            priority: 8 # Number between 0 and 15
            mode: "MSTP" # or "RPVST"

        # Configure SpanningTree for port 5
        - name: Configure SpanningTree for port
          include: aruba_task_lists/aos_switch/spanning_tree_port.yml
          vars:
            port: "5" # String of port number or name
            priority: 10 # Number between 0 and 15
            admin_edge_port: True # or False
            bpdu_protection: True # or False
            bpdu_filter: True # or False
            root_guard: True # or False

      always:
        # Logout from ArubaOS Switch
        - name: Logout
          include: aruba_task_lists/aos_switch/logout_switch.yml

